language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: heroku
  api_key:
    secure: $heroku_token
  app: jumpstart-portfolios-site
  on:
    repo: thoughtworks-jumpstart/jumpstart-portfolios-site
